CodeSearch/CodeSearchApp/CodeSearchDemo/Controllers/FileSearchController.cs
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.DirectoryServices.ActiveDirectory;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Mime;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using CodeSearchDemo.Models;
using Lucene.Net.Analysis;
using Lucene.Net.Analysis.Standard;
using Lucene.Net.Documents;
using Lucene.Net.Index;
using Lucene.Net.QueryParsers;
using Lucene.Net.Search;
using Lucene.Net.Search.Spans;
using Lucene.Net.Store;
using Microsoft.Ajax.Utilities;
using PagedList;
using Directory = Lucene.Net.Store.Directory;
using Version = Lucene.Net.Util.Version;
using Microsoft.AspNet.SignalR;
using Timer = System.Timers.Timer;

namespace CodeSearchDemo.Controllers
{
    public class FileSearchController : AsyncController 
    {
        private const int MAX_RESULTS_PER_PAGE = 20;

        private const string LAST_UPDATE_FILE = "UpdateTime.txt";

        private const int CONFIGURATION_TECHNOLOGY = 5;
        private const int CONFIGURATION_LAYER = 4;
        private const int CONFIGURATION_DOMAIN = 3;
        private const int CONFIGURATION_PROJECT_NAME = 2;

        
        /// <summary>
        /// List of all branches
        /// </summary>
        private  List<string> _branchesList;


        /// <summary>
        /// Get the last update time of index path
        /// </summary>
        /// <param name="indexPath">Index directory</param>
        /// <returns>The last update time</returns>
        private static DateTime GetLastUpdateTime(string indexPath)
        {
            DateTime dt = new DateTime(1900, 1, 1, 0, 0, 0);
            string UpdateFilePath = Path.Combine(indexPath, LAST_UPDATE_FILE);

            try
            {
                if (System.IO.File.Exists(UpdateFilePath))
                {
                    dt = DateTime.Parse(System.IO.File.ReadAllText(UpdateFilePath));
                }
            }
            catch (Exception)
            {

                dt = new DateTime(1900, 1, 1, 0, 0, 0);
            }

            return dt;
        }

        /// <summary>
        /// Get the current working directory of all indexes
        /// </summary>
        /// <returns>The most up-to-date working directory</returns>
        public static string GetIndexPath()
        {
            string firstIndexPath = WebConfigurationManager.AppSettings["FirstRootPath"];
            string secondIndexPath = WebConfigurationManager.AppSettings["SecondRootPath"];

            return GetLastUpdateTime(secondIndexPath) > GetLastUpdateTime(firstIndexPath)
                ? secondIndexPath
                : firstIndexPath;
        }


        /// <summary>
        /// Get all branches
        /// </summary>
        private void GetBranches()
        {

            if (Session["branches"] == null)
            {
                string path = GetIndexPath();
                _branchesList = new List<string>();
                _branchesList.Add("Configuration");
                _branchesList.Add("Trunk");
                foreach (string dirName in System.IO.Directory.GetDirectories(path).Select(s => s.Remove(0, path.Length + 1)).Where(dirName => !dirName.Equals("Configuration") && !dirName.Equals("Trunk")))
                {
                    _branchesList.Add(dirName);
                }


                Session["branches"] = _branchesList;


            }
            else
            {
                _branchesList = Session["branches"] as List<string>;
            }


        }

        //
        // GET: /FileSearch/

        public ActionResult Index()
        {
                     
            ViewBag.BranchesDropDownList = new SelectList(new List<string>());   
            return View("FirstPageView");
            

        }

        [HttpGet]
        public void LoadBranchesAsync()
        {
            AsyncManager.OutstandingOperations.Increment();
            Task.Run(() =>
            {
                GetBranches();
                AsyncManager.OutstandingOperations.Decrement();
            });

        }

        public ActionResult LoadBranchesCompleted()
        {
            List<FileSearchModel> results = new List<FileSearchModel>();
            ViewBag.BranchesDropDownList = new SelectList(_branchesList);


            return View("FileSearchView", results.ToPagedList(1, MAX_RESULTS_PER_PAGE));
        }



        [HttpGet]
        public void SearchInFilesAsync(string token, string branch, string layer, string connectionID, int? page)
        {
            Stopwatch stopWatch = new Stopwatch();
            stopWatch.Reset();
            stopWatch.Start();
            if (!string.IsNullOrEmpty(token))
            {
                ProgressHub.SendMessage(
                            string.Format("Start collecting results for token \"{0}\" of branch {1}", token, branch), 0,
                            connectionID);
            }

            AsyncManager.OutstandingOperations.Increment();

            Task.Run(() =>
            {
                
                
                GetBranches();
                ViewBag.BranchesDropDownList = new SelectList(_branchesList);

                List<FileSearchModel> lastSearchResults = null;

                if (string.IsNullOrEmpty(token))
                {
                    ModelState.AddModelError("Error", "Search text cannot be empty!");
                    AsyncManager.Parameters["lastSearchResults"] = new List<FileSearchModel>();
                    AsyncManager.Parameters["currentIndex"] = 1;
                    AsyncManager.OutstandingOperations.Decrement();
                }
                else
                {
                    ViewBag.Currenttoken = token;
                    ViewBag.Currentbranch = branch;
                    ViewBag.Currentlayer = layer;
                    ViewBag.CurrentconnectionID = connectionID;



                    lastSearchResults = Session["LastSearchResults"] as List<FileSearchModel>;
                    string searchMessage = Session["searchMessage"] as string;


                    int currentIndex = page ?? 1;

                    if (!page.HasValue || lastSearchResults == null)
                    {

                        ConcurrentDictionary<string, FileSearchModel> searchDictionaryConcurrent =
                            new ConcurrentDictionary<string, FileSearchModel>();

                        string indexPath = GetIndexPath();
                        Directory luceneIndexDirectory = FSDirectory.Open(Path.Combine(indexPath, branch));




                        IndexSearcher searcher = new IndexSearcher(luceneIndexDirectory);
                        BooleanQuery bq = new BooleanQuery();


                        foreach (string word in token.Split(' '))
                        {
                            if (word.Contains("*"))
                            {
                                Query textQuery = new PrefixQuery(new Term("LineText", word));
                                bq.Add(textQuery, Occur.MUST);
                            }
                            else
                            {
                                string wildWord = "*" + word + "*";
                                Query textQuery = new WildcardQuery(new Term("LineText", wildWord));
                                bq.Add(textQuery, Occur.MUST);
                            }



                        }



                        if (!string.IsNullOrEmpty(layer))
                        {
                            BooleanQuery layerQuery = new BooleanQuery();
                            layerQuery.Add(new TermQuery(new Term("Layer", "Common")), Occur.SHOULD);
                            layerQuery.Add(new TermQuery(new Term("Layer", layer)), Occur.SHOULD);
                            bq.Add(layerQuery, Occur.MUST);
                        }

                        int searchCounter = 5;
                        var waitHandle = new EventWaitHandle(false, EventResetMode.AutoReset);


                        Task.Run(() =>
                        {
                            do
                            {
                                ProgressHub.SendMessage(
                                string.Format("Collecting results for token \"{0}\" of branch {1}", token, branch), (searchCounter) % 100,
                                connectionID);
                                searchCounter += 5;
                            } while (!waitHandle.WaitOne(TimeSpan.FromSeconds(1)));
              
                        });

                        Lucene.Net.Search.TopDocs results = searcher.Search(bq, null, 200000);
                        waitHandle.Set();

                        

                        object sync = new object();

                        int counter = 1;

                        //Calculate what is the 5% of the total results
                        double percentage = (5.0 *results.ScoreDocs.Count()/100);

                        Parallel.ForEach(results.ScoreDocs, scoreDoc =>
                        {
                            Task.Run(() =>
                            {
                                int curCounter;
                                lock (sync)
                                {
                                    curCounter = counter++;
                                }

                                if ((curCounter % Math.Ceiling(percentage)) == 0)
                                {
                                    ProgressHub.SendMessage(
                                        string.Format("Processing results {0} of {1}", curCounter, results.ScoreDocs.Count()),
                                        curCounter * 100 / results.ScoreDocs.Count(), connectionID);
                                }

CodeSearch/CodeSearchApp/CodeSearchDemo/Views/FileSearch/DisplayFileView.cshtml
@using PagedList.Mvc
@model CodeSearchDemo.Models.DisplayFileModel

@{
    ViewBag.Title = "Display File View";
}


@if(Request.UrlReferrer != null)
{
     <button type="button" onclick="history.go(-1); return false;" >Back</button>
 } 

<h2>@Model.FileNameForDisplay</h2>



@{
    Html.RenderAction("GetDiffBranches","Diff", new {relativeFilePath = @Model.RelativeFilePath, branch = @Model.Branch, uri = @Model.Uri});
}
<table style="border-spacing: 0;border-collapse: collapse;padding-bottom: 0;padding-top: 0;margin-top: 0.5em; margin-bottom: 0.5em">
        @for (var i = 0; i < @Model.Lines.ToArray().Length; i++)
        {

            if (@Model.RowNumbers.Contains(i))
            {
                <tr style="text-align: left; width: 1500px; height: 0.3em;padding-top: 0;padding-bottom: 0;margin-bottom: 0.5em;margin-top: 0.5em;">
                    <td style="font-size: 1.5em;padding-top: 0px; padding-bottom: 0px;width: 1500px;height: 0.3em;margin-bottom: 0.5em;margin-top: 0.5em;border-bottom: 1px">
                        <pre class="before" style="padding-top: 0px; padding-bottom: 0px; width: 1500px; height: 0.3em; margin-bottom: 0.5em; margin-top: 0.5em;border-bottom: 1px"><span class="display" style="background-color:yellow;font-weight: bold;">@Model.Lines[i]</span></pre>
                    </td>
                </tr>
            }
            else
            {
                <tr style="text-align: left; width: 1500px;  height: 0.1em;padding-top: 0;padding-bottom: 0;margin-bottom: 0.5em;margin-top: 0.5em;">
                    <td style="font-size: 1.5em;padding-top : 0px;padding-bottom: 0px;width: 1500px;height: 0.1em;margin-bottom: 0.5em;margin-top: 0.5em;border-bottom: 1px">
                        <pre class="before" style="padding-top : 0px;padding-bottom: 0px;width: 1500px;height: 0.1em;margin-bottom: 0.5em;margin-top: 0.5em;border-bottom: 1px"><span class="display" >@Model.Lines[i]</span></pre>
                    </td>
                </tr>
            }

        }
    </table>
 
   
<br />

    @if(Request.UrlReferrer != null)
    {
        <button type="button" onclick="history.go(-1); return false;" >Back</button>
    } 

CodeSearch/CodeSearchApp/CodeSearchDemo/Views/FileSearch/FileSearchView.cshtml
@using System.Collections
@using System.Diagnostics.Eventing.Reader
@using PagedList.Mvc;
@model PagedList.IPagedList<CodeSearchDemo.Models.FileSearchModel> 
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<link type="text/css" href="/~Content/ui.all.css" rel="stylesheet" />
<link href="~/Content/themes/base/minified/jquery-ui.min.css" rel="stylesheet" type="text/css" />
<script src="http://ajax.microsoft.com/ajax/jquery/jquery-1.4.2.js" type="text/javascript"></script>
<script src="http://ajax.microsoft.com/ajax/jquery.validate/1.7/jquery.validate.min.js" type="text/javascript"></script>

@{
    ViewBag.Title = "UMD Code search";
}

<!-- signalr library -->

<!-- autogenerated signalr hub script -->



    @section scripts {
        @Scripts.Render("~/bundles/signalR")
        <script src="../../Scripts/json2.min.js"></script>
        <script src="../../Scripts/jquery.signalR-2.0.2.min.js"></script>
        <script src="../../Scripts/jquery-ui-1.8.24.js"></script>
        <script src="/signalr/hubs"></script>
        <script>
            $(document).ready(function() {


                $("#progressbar").progressbar({ value: 0 });
                $("#progressbar").hide();
                $("#progressbar").css({ 'background': 'LightYellow' });
                $("#progressbar > div").css({ 'background': 'green' });

                // initialize the connection to the server
                var progressNotifier = $.connection.progressHub;

                // client-side sendMessage function that will be called from the server-side
                progressNotifier.client.sendMessage = function (message, count) {
                    // update progress
                    UpdateProgress(message, count);
                };

                // establish the connection to the server and start server-side operation
                $.connection.hub.start({ jsonp: true }).done(function () {

                    $('#connectionID').val($.connection.hub.id);

                    
                });
               
            });

            function UpdateProgress(message, count) {

                
                // get result div
                var result = $("#result");
                // set message
                result.html(message);

                if (!message || 0 == message.length) {
                    $("#progressbar").hide();
                } else {
                    
                    $("#progressbar").show();
                    // update progress bar
                    $("#progressbar").progressbar("value", count);
                }


                
            }
        </script>
    }

<script>
    function keypressHandler(e) {
        if (e.which == 13) {
            $(this).blur();
            $('#SearchButton').focus().click();//give your submit an ID
        }
    }

    $('#fileSearchForm').keypress(keypressHandler);
</script>

<script>
    function clear() {
        
        $('#searchResult').text("");
        if ($('#noResult').length > 0) {
            
            $('#noResult').text("");
        }
    }

</script>






<p>
    <img src= "@Url.Content("~/Images2/Search.jpg")" alt="IMAGES" style="width: 150px; height: 150px; display:block;float:right; margin-right: 30em ;background-color: green" />
</p>
<h2>Search for a class, property or method:</h2>

<p> 
   


            @using (Html.BeginForm("SearchInFiles", "FileSearch", FormMethod.Get, new {id = "fileSearchForm"}))
            {

                <p> <b>Text:</b> @Html.TextBox("token") 

                    <b>Branch:</b> @Html.DropDownList("branch", (SelectList) ViewBag.BranchesDropDownList, new {@class = "dropdown"})  
            

                    <b>Layer:</b> @Html.DropDownList("layer", new List<SelectListItem>
                                  {
                                      new SelectListItem {Text = "All", Value = ""},
                                      new SelectListItem {Text = "Access", Value = "Access"},
                                      new SelectListItem {Text = "CCFlow", Value = "CCFlow"},
                                      new SelectListItem {Text = "Core", Value = "Core"},
                                      new SelectListItem {Text = "Delivery", Value = "Delivery"},
                                      new SelectListItem {Text = "NRG", Value = "NRG"},
                                      new SelectListItem {Text = "Targeting", Value = "Targeting"}

                                  },
                                      new {@class = "dropdown"})  
             
                    @Html.Hidden("connectionID", "firstID")
                    <input type="submit" name="SearchButton" id="submitID" value="Go" onclick="clear();" />
           
           
            
                </p>
                <p>
                    @Html.ValidationMessage("Error")
                </p>
                <div id="result" style="font-family: Tahoma; font-size: 2em; color: black; margin-top: 10px; padding-bottom: 5px"></div>

                <div id="progressbar" style="width: 600px; height: 30px;"></div>

                <br />

            }
 
    
    <div id="searchResult" style="font-family: Tahoma; font-size: 0.9em; color: blue; margin-top: 1px; padding-bottom: 3px">@ViewBag.SearchMessage</div>   
    @Html.PagedListPager((PagedList.IPagedList)Model, page => Url.Action("SearchInFiles",
    new { token = ViewBag.Currenttoken, branch = ViewBag.Currentbranch, layer = ViewBag.Currentlayer, connectionID = ViewBag.CurrentconnectionID, page = page }))
    
    @if (Model.Count == 0 && !string.IsNullOrEmpty(ViewBag.Currenttoken))
    {
        <div id="noResult" style="font-family: Tahoma; font-size: 2em; color: red; margin-top: 10px; padding-bottom: 5px">No results have been found for "@ViewBag.Currenttoken"</div>
    }

    @foreach (var item in Model)
            {

             <table>
                 <tr style="text-align: left; width: 1500px">
                     
                     @Html.ActionLink(item.FileNameForDisplay, "DisplayFile", new {fileName = item.FileName, rowNumbersStr = string.Join(",", item.RowNumbers.ToArray()), branch = item.Branch}, "FileSearch")

                 </tr>
                 
                 @foreach (var line in item.Lines)
                 {
                     <tr style="background-color: #FFFF66; text-align: left; width: 1500px">
                         <td class="col1">
                             @Html.DisplayFor(modelItem => line)
                         </td>
                     </tr>
                 }
                 
                 
             </table>

            }
            <br />



            Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager((PagedList.IPagedList)Model, page => Url.Action("SearchInFiles",
    new { token = ViewBag.Currenttoken, branch = ViewBag.Currentbranch, layer = ViewBag.Currentlayer, connectionID = ViewBag.CurrentconnectionID, page = page }))
</p>

CodeSearch/CodeSearchApp/CodeSearchDemo/Views/FileSearch/FirstPageView.cshtml
@{
    ViewBag.Title = "UMD Code search";
}

 <p> <b>Text:</b> @Html.TextBox("token") 

            <b>Branch:</b> @Html.DropDownList("branch", (SelectList)ViewBag.BranchesDropDownList, new { @class = "dropdown" })  
            

            <b>Layer:</b> @Html.DropDownList("layer", new List<SelectListItem>
                          {
                              new SelectListItem {Text = "All", Value = ""},
                              new SelectListItem {Text = "Access", Value = "Access"},
                              new SelectListItem {Text = "CCFlow", Value = "CCFlow"},
                              new SelectListItem {Text = "Core", Value = "Core"},
                              new SelectListItem {Text = "Delivery", Value = "Delivery"},
                              new SelectListItem {Text = "Targeting", Value = "Targeting"}

                          },
                              new { @class = "dropdown" })  
             
            @Html.Hidden("connectionID", "firstID")

                   
            
        </p>
        <div id="waitMessage" style="font-family: Tahoma; font-size: 2em; color: red; margin-top: 10px; padding-bottom: 5px">Please wait while loading all available branches</div>
<script>
    window.location.href = "@Url.Action("LoadBranches","FileSearch")"
</script>
        

CodeSearch/CodeSearchApp/CodeSearchDemo/Views/FileSearch/Index.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>title</h2>